//ALGORITMO QUE SOLICITE 15 NUMEROS Y DETERMINE CUANTOS SON POSITIVOS ,NEGATIVOS Y CEROS

/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.TALEER;
import java.util.Scanner;
public class App {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);

        int numero;
        int positivos = 0;
        int negativos = 0;
        int ceros = 0;

        System.out.println("PROGRAMA PARA ANALIZAR 15 NUMEROS");

        for(int i = 1; i <= 15; i++) {

            System.out.println("====================");
            System.out.println("Ingrese el numero #" + i);
            numero = sc.nextInt();

            // POSITIVO, NEGATIVO O CERO
            if(numero > 0) {
                positivos++;

            } else if(numero < 0) {
                negativos++;

            } else {
                ceros++;
            }

            // PAR O IMPAR
            if(numero % 2 == 0) {
                System.out.println("El numero es PAR");

            } else {
                System.out.println("El numero es IMPAR");
            }
        }

        // RESULTADOS
        System.out.println("====================");
        System.out.println("RESULTADOS FINALES");
        System.out.println("====================");

        System.out.println("Positivos: " + positivos);
        System.out.println("Negativos: " + negativos);
        System.out.println("Ceros: " + ceros);

        sc.close();
    }
}